name: Sample Workflow
run-name: Testing
on: [push]
jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - run: python --version
  
  check-docker-installation:
    runs-on: ubuntu-latest
    steps:
      - run: docker --version
      - run: docker pull yash301998/flask-weather-app:v1
      - run: docker run -d -p 5000:5000 yash301998/flask-weather-app:v1
      - run: docker ps
    
